#ifndef _XML_H_
#define _XML_H_
//for other users of this lib,they only need to include this file
#include "assert.h"
#include "XMLError.h"

#include "XMLNode.h"
#include "XMLElement.h"
#include "XMLAttribute.h"
#include "XMLText.h"
#include "XMLCDataSection.h"
#include "XMLEntityRef.h"
#include "XMLEntity.h"
#include "XMLPI.h"
#include "XMLComment.h"
#include "XMLTree.h"
#include "XMLDocType.h"
#include "XMLDocFrag.h"
#include "XMLNotation.h"

#include "XMLNodeList.h"
#include "XMLNodeMap.h"

#include "XMLParseError.h"

#endif